Update to v0.14.0-rc3
purescript-web/purescript-web-cssom pull request #7
Opened 2020-12-08 15:56 UTC by JordanMartinez

Backlinking to purescript/purescript#3942

2020-12-08 22:30 UTC, kl0tl approved these changes

2020-12-08 22:38 UTC, kl0tl commented on spago.dhall
> +-}
Shall we remove this comment?

2020-12-09 00:56 UTC, thomashoneyman commented on .github/workflows/ci.yml
> +on: [push, pull_request]
```suggestion
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
```

2020-12-09 00:56 UTC, thomashoneyman commented on spago.dhall
> +-}
```suggestion
```

2020-12-09 00:57 UTC, thomashoneyman requested changes

2020-12-09 00:57 UTC, thomashoneyman commented on spago.dhall
> +, sources = [ "src/**/*.purs", "test/**/*.purs" ]
```suggestion
, sources = [ "src/**/*.purs" ]
```

We can either trim the sources or add a dummy test.

2020-12-10 22:35 UTC, thomashoneyman commented
@JordanMartinez looks like this library was missed when updating them all to 0.14.0-rc3 with Bower.

2020-12-11 01:09 UTC, JordanMartinez commented
@thomashoneyman Thanks. I've updated my PR to use bower rather than Spago

2020-12-11 01:15 UTC, JordanMartinez commented
CI builds

2020-12-11 01:36 UTC, merged